apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: orderservice-sidecar
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: orderservice
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
  - targetPort: 9090
    path: /metrics
    interval: 15s
    relabelings:
      - action: replace
        replacement: orderservice-dapr
        targetLabel: service 
  - port: http
    path: /metrics
    interval: 15s