apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderservice"
        dapr.io/app-port: "3200"
        dapr.io/metrics-port: "9090"
    spec:
      containers:
      - name: orderservice
        image: timspitters03/tswms-orderservice:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3200
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Kubernetes"
        - name: ASPNETCORE_URLS
          value: "http://+:3200"
        - name: ConnectionStrings__OrderServiceDatabase
          value: "Server=db-order;Database=OrderServiceDb;User Id=sa;Password=TimTest123;Encrypt=False;"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"