apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: orderservice
  namespace: default
  labels:
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: orderservice
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: 15s
  - targetPort: 9090
    path: /
    interval: 15s