apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: orderservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: orderservice
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: 15s
