apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-order
  template:
    metadata:
      labels:
        app: db-order
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/azure-sql-edge:latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "TimTest123"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: db-order
spec:
  selector:
    app: db-order
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433