services:
  orderservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: tswms-orderservice:dev-latest
    container_name: TSWMS-OrderService
    ports:
      - "3200:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=UserServiceDb;User Id=sa;Password=TimTest123;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: TSWMS-OrderService-MSSQL-DB
    environment:
      SA_PASSWORD: "TimTest123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: