name: OrderService - Build, Test, and Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore NuGet packages
        run: dotnet restore
        working-directory: TSWMS.OrderService/TSWMS.OrderService.Api

      - name: Build the project
        run: dotnet build --configuration Release --no-restore
        working-directory: TSWMS.OrderService/TSWMS.OrderService.Api

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install Coverlet Console
        run: dotnet tool install --global coverlet.console

      - name: Restore dependencies for all test projects
        run: dotnet restore
        working-directory: TSWMS.OrderService

      - name: Run Code Coverage with Coverlet for Integration Tests
        run: |
          coverlet TSWMS.OrderService/TSWMS.OrderService.Api.IntegrationTests/bin/Release/net8.0/TSWMS.OrderService.Api.IntegrationTests.dll \
          --target "dotnet" \
          --targetargs "test TSWMS.OrderService/TSWMS.OrderService.Api.IntegrationTests/TSWMS.OrderService.Api.IntegrationTests.csproj --no-build" \
          --format opencover \
          --output coverage.integration.xml

      - name: Run Code Coverage with Coverlet for Business Unit Tests
        run: |
          coverlet TSWMS.OrderService/TSWMS.OrderService.Business.UnitTests/bin/Release/net8.0/TSWMS.OrderService.Business.UnitTests.dll \
          --target "dotnet" \
          --targetargs "test TSWMS.OrderService/TSWMS.OrderService.Business.UnitTests/TSWMS.OrderService.Business.UnitTests.csproj --no-build" \
          --format opencover \
          --output coverage.business.xml

      - name: Run Code Coverage with Coverlet for Data Unit Tests
        run: |
          coverlet TSWMS.OrderService/TSWMS.OrderService.Data.UnitTests/bin/Release/net8.0/TSWMS.OrderService.Data.UnitTests.dll \
          --target "dotnet" \
          --targetargs "test TSWMS.OrderService/TSWMS.OrderService.Data.UnitTests/TSWMS.OrderService.Data.UnitTests.csproj --no-build" \
          --format opencover \
          --output coverage.data.xml

  sonarcloud:
    name: sonarcloud analysis
    runs-on: windows-latest
    needs: [test]

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Add SonarCloud scanner to PATH
        shell: powershell
        run: |
          $Env:PATH += ";$(pwd)\.sonar\scanner"

      - name: Build and analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .sonar\scanner\dotnet-sonarscanner begin /k:"Timmehss_TSWMS" /o:"tswms" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.cs.opencover.reportsPaths="coverage.integration.xml,coverage.business.xml,coverage.data.xml" \
          /d:sonar.host.url="https://sonarcloud.io"
          dotnet build TSWMS.OrderService/TSWMS.OrderService.sln
          .sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  docker:
    runs-on: ubuntu-latest
    needs: [test, sonarcloud]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: TSWMS.OrderService
          file: TSWMS.OrderService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tswms-orderservice:dev-latest