name: OrderService - Build, Test, and Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  sonarcloud:
    name: Build, Test, and Analyze with Coverage
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Build and Analyze with Coverlet Coverage
        run: |
            .\.sonar\scanner\dotnet-sonarscanner begin `
              /k:"Timmehss_TSWMS" `
              /o:"tswms" `
              /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
              /d:sonar.host.url="https://sonarcloud.io" `
              /d:sonar.cs.cobertura.reportsPaths="TestResults/**/coverage.cobertura.xml" `
              /d:sonar.exclusions="**/build-wrapper-dump.json" `
              # /d:sonar.coverage.exclusions="TSWMS.OrderService.Data/Migrations/**/*.cs,TSWMS.OrderService.Data/OrdersDbContext.cs" `
              # /d:sonar.test.inclusions="**/TSWMS.OrderService.Data.UnitTests/**/*.cs" `
              /d:sonar.cs.testProjectPattern=".*\.UnitTests"
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-incremental

      - name: Run Unit Tests with Coverage
        run: |
          dotnet test TSWMS.OrderService.Data.UnitTests/TSWMS.OrderService.Data.UnitTests.csproj `
            --collect:"XPlat Code Coverage" `
            --results-directory:"TestResults"
        shell: pwsh

      - name: List files in TestResults directory (debugging)
        run: |
          Write-Host "Listing files in TestResults directory"
          Get-ChildItem -Path TestResults -Recurse
        shell: pwsh

      - name: Show coverage XML (optional)
        run: |
          $coverageFile = Get-ChildItem -Path TestResults -Recurse -Filter 'coverage.cobertura.xml'
          if ($coverageFile) {
            Write-Host "Found coverage file. Displaying content:"
            Get-Content -Path $coverageFile.FullName
          } else {
            Write-Host "Coverage file not found."
          }
        shell: pwsh

      - name: End SonarCloud analysis
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        shell: pwsh

  docker:
    runs-on: ubuntu-latest
    needs: [sonarcloud]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tswms-orderservice:dev-latest
